# toml 配置
# toml和json中,值中数字必须使用字符串格式

# 公共配置项
[common_conf_item]
max_log_files = "3"
single_log_max_size = "104857600"

# 公共配置文件
[common_conf_file]
"seelog.xml" = "1"

# 个性化配置
[individual_conf_file.online]
files = [
    "kafka_consumer_conf.json",
    "kafka_producer_conf.json",
    "kafka_monitor_conf.json"
]
[individual_conf_file.online.hosts."192.168.0.21_6601"]
suffix = "1"                # 对应的个性化配置文件为 kafka_consumer_conf1.json,kafka_producer_conf1.json,kafka_monitor_conf1.json 即位于文件名与扩展名之间

[individual_conf_file.sandbox]
files = [
    "kafka_consumer_conf.json",
    "kafka_producer_conf.json",
    "kafka_monitor_conf.json"
]
[individual_conf_file.sandbox.hosts."192.168.0.21_6601"]
suffix = ""                # 对应的个性化配置文件为 kafka_consumer_conf.json,kafka_producer_conf.json,kafka_monitor_conf.json   无后缀可不配置 默认无后缀
[individual_conf_file.sandbox.hosts."192.168.0.21_6600"]
suffix = "2"               # 对应的个性化配置文件为 kafka_consumer_conf2.json,kafka_producer_conf2.json,kafka_monitor_conf2.json 即位于文件名与扩展名之间